---
version: "3.9"

services:
  loki:
    image: grafana/loki:2.5.0
    container_name: grafana-loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    networks:
      - lokinet
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${SERVICE}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE}.middlewares=auth"

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /var/log:/var/log:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - lokinet

networks:
  lokinet:
    internal: true
  traefik:
    external: true
