---
version: "3.9"

networks:
  proxy:
    name: traefik

services:
  loki:
    image: grafana/loki:2.5.0
#    ports:
#      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.tls=true"
      - "traefik.http.routers.gateway.tls.certresolver=encrypt-resolver"
      - "traefik.http.routers.gateway.rule=Host(`loki-gr3.cefim-formation.org`)"
      - "traefik.http.routers.gateway.entrypoints=websecure"

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - proxy
