version: "3.7"

services:
  sonarqube:
    image: sonarqube
    networks:
      - lan-traefik
    volumes:
      # - "conf:/opt/sonarqube/conf"
      - "extensions:/opt/sonarqube/extensions"
      - "logs:/opt/sonarqube/logs"
      - "data:/opt/sonarqube/data"
    depends_on:
      - postgres
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgres/sonarqube
    deploy: 
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarqube.rule=Host(`sonarqube-gr3.cefim-formation.org`)"
      - "traefik.http.routers.sonarqube.entrypoints=https"
      - "traefik.http.services.sonarqube.loadbalancer.server.port=3000"

  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - lan-traefik      
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
      PGDATA: pg_data:/var/lib/postgresql/data/pgdata

volumes:
  data:
  logs:
  extensions:
  pg_data:

networks:
  lan-traefik:
    name: lan-traefik
