---
version: "3.9"

services:
  sonarqube:
    image: sonarqube
    networks:
      - traefik
      - sonarnet
    volumes:
      # - "conf:/opt/sonarqube/conf"
      - "extensions:/opt/sonarqube/extensions"
      - "logs:/opt/sonarqube/logs"
      - "data:/opt/sonarqube/data"
    depends_on:
      - postgres
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgres/sonarqube
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.sonarqube.rule=Host(`sonarqube-gr3.cefim-formation.org`)"
      - "traefik.http.routers.sonarqube.entrypoints=websecure"

  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
      PGDATA: pg_data:/var/lib/postgresql/data/pgdata

volumes:
  data:
  logs:
  extensions:
  pg_data:

networks:
  sonarnet:
    internal: true
  traefik:
    external: true
