---
image: registry-gr3.cefim-formation.org/devops/ubuntu-ssh

stages:
  - deploy

.generic-deploy-job:
  variables:
    DEPLOY_HOST: "Docker_gr3"
  script:
    - ssh $DEPLOY_HOST "mkdir -p ~/${CI_PROJECT_NAME}_deploy/$rep/"
    - scp -r ./$rep/* $DEPLOY_HOST:~/${CI_PROJECT_NAME}_deploy/$rep/
    - scp ~/.env $DEPLOY_HOST:~/${CI_PROJECT_NAME}_deploy/$rep/
    - ssh $DEPLOY_HOST "echo ${CI_REGISTRY_PASSWORD} | sudo docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}"
    - ssh $DEPLOY_HOST "cd ~/${CI_PROJECT_NAME}_deploy/$rep/ && sudo docker compose pull && sudo docker compose up -d"

grafana-deploy-job:
  extends: .generic-deploy-job
  stage: deploy
  variables:
    rep: grafana
  script:
    - echo "$GRAFANA_ENV" > ~/.env
    - !reference [.generic-deploy-job, script]
  when: manual

loki-deploy-job:
  extends: .generic-deploy-job
  stage: deploy
  variables:
    rep: loki
  script:
    - echo "$LOKI_ENV" > ~/.env
    - !reference [.generic-deploy-job, script]
  when: manual

prometheus-deploy-job:
  extends: .generic-deploy-job
  stage: deploy
  variables:
    rep: prometheus
  script:
    - echo "$PROMETHEUS_ENV" > ~/.env
    - !reference [.generic-deploy-job, script]
  when: manual

sonarqube-deploy-job:
  extends: .generic-deploy-job
  stage: deploy
  variables:
    rep: sonarqube
  script:
    - echo "$SONARQUBE_ENV" > ~/.env
    - !reference [.generic-deploy-job, script]
  when: manual

harbor-deploy-job:
  extends: .generic-deploy-job
  stage: deploy
  variables:
    rep: harbor
  script:
    - echo "$HARBOR_ENV" > ~/.env
    - !reference [.generic-deploy-job, script]
  when: manual

traefik-deploy-job:
  extends: .generic-deploy-job
  stage: deploy
  variables:
    rep: traefik
  script:
    - ssh $DEPLOY_HOST "mkdir -p ~/${CI_PROJECT_NAME}_deploy/traefik/data/"
    - echo "$TRAEFIK_ENV" > ~/.env
    - echo "$PASSWD" > ~/.passwd
    - scp ~/.passwd $DEPLOY_HOST:~/${CI_PROJECT_NAME}_deploy/traefik/data
    - echo "$ACME_JSON" > ~/acme.json
    - chmod 600 ~/acme.json
    - scp ~/acme.json $DEPLOY_HOST:~/${CI_PROJECT_NAME}_deploy/traefik/data
    - !reference [.generic-deploy-job, script]
  when: manual
