---
version: '3.9'

services:
  prometheus:
    image: prom/prometheus
#    ports:
#      - 9000:9090
    networks:
      - proxy
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus-gr3.cefim-formation.org`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.middlewares=auth"

volumes:
  prometheus-data:

networks: 
  proxy:
    external:
      name: traefik