---
version: "3.9"

services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./mdp/passwd:/etc/traefik/passwd
      - /etc/localtime:/etc/localtime:ro
      - ./log:/log
      - ./data/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - traefik.docker.network=traefik
      - "traefik.http.routers.traefik.rule=Host(`traefik-gr3.cefim-formation.org`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
#      - "traefik.http.routers.traefik.middlewares=auth"
#      - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/passwd"

networks:
  traefik:
    external: true
