---
version: "3.9"

services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik.yml:/etc/traefik/traefik.yml:ro

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
#      - "traefik.http.routers.whoami.rule=Host(`ec2-13-38-30-207.eu-west-3.compute.amazonaws.com`)"
      - "traefik.http.routers.whoami.entrypoints=web"