---
api:
  insecure: false
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: :443
    http:
      tls:
        certResolver: encrypt-resolver

certificatesResolvers:
  encrypt-resolver:
    acme:
      email: "admin@${DOMAIN}"
      storage: "acme.json"
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
    watch: true

log:
  filePath: "/log/traefik.log"
  format: json
  level: ERROR

accessLog:
  filePath: "/log/access.log"
  format: json

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    entryPoint: websecure
    