---
version: '3.9'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - default
    restart: unless-stopped
    volumes:
      - ./datasources:/etc/grafana/datasources
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:

networks: 
  default: 
    name: external-example