---
version: '3.9'

services:
  grafana:
    image: grafana/grafana
    networks:
      - traefik-net
    restart: unless-stopped
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${SERVICE}.entrypoints=websecure"

volumes:
  grafana-data:

networks:
  traefik-net:
    external: true
