version: '3'

volumes:
  grafana-pgdata:

services:
  # Grafana dedicated storage
  #
  grafana-storage:
    image: postgres:10-alpine
    networks:
      - lan-traefik
    volumes:
      - grafana-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=grafana
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 1s
      retries: 5

        
  # Grafana Server
  #
  grafana:
    image: grafana/grafana
#    ports:
#      - "3000:3000"
    networks:
      - lan-traefik
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=grafana-storage
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=admin
      - GF_DATABASE_PASSWORD=password
    deploy: 
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik-gr3.cefim-formation.org`)"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  lan-traefik:
    name: lan-traefik